### PR TITLE
[#303] fixed padding and vertical alignment within mobile view

### PR DESCRIPTION
**Pull request by FarazA22**

### CODE REVIEW

**Comment by FarazA22** [comment]
Hey @carye3, I have a question about spacing between the 'back to roadmap' button and 'mini road map' component on the individual task screen. The design created by Guy has 20 pixels of spacing between the two. When implementing the code, we added additional spacing between the components. I'd like you input on whether we should keep 20 pixels of spacing between both components or add more white space to the design.

> Figma - there is 20 pixels of spacing between the button and the top of the icon
> Screen Shot 2021-08-27 at 4 36 27 PM

> Currently in the Dev environment / additional spacing added
> image

> UI without additional spacing
> Screen Shot 2021-08-27 at 4 41 52 PM

**Comment by carye3** [comment]
@FarazA22 thanks for your patience... let's keep the spacing however, i think the text of "Back to Roadmap" should be left aligned with the roadmap below it ([Figma link](https://www.figma.com/file/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?node-id=4760%3A102362)). 

image

You might notice some inconsistency in link styles (eg internal to navigator vs external links) -- that needs to be addressed in ticket #171 

First need approval from @skeeJay ?

**Comment by aloverso** [comment]
@carye3 I don't want to block this story (addressing whitespace changes that came from the navbar update) on a new requirement. I think that adjusting the Back To Roadmap styling for aligning the text differently should be tracked in a different story. We could do it during des/dev pairing, or just have a new story for it

**Comment by aloverso** [comment]
Decisions made during dev/des pair. To complete this story:

- [ ] spacing between Back To Roadmap button & Mini-Roadmap should be the larger option (in line with current staging env)
- [ ] spacing between navbar & rest of content on mobile should be smaller (in line with current staging env)

**Pull request merged**
